# -*- coding: utf-8 -*-
"""KNN_implementation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19E6gY6otHqGnV7pKTkArN-tdP7vHvp5G
"""

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score

"""Cargamos el data set obtenido sckilearn"""

iris = load_iris()
X = iris.data
y = iris.target

"""We divide our dataset"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

"""Here we define our neighbors"""

knn = KNeighborsClassifier(n_neighbors=3)

"""Starting the training"""

knn.fit(X_train, y_train)
predictions = knn.predict(X_test)

accuracy = accuracy_score(y_test, predictions)
print("Precisión del modelo KNN:", accuracy)